server:
  port:
    28852
spring:
  application:
    name: oauth-social-app
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./social_app_db
    password:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:28852
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            clientId: Iv23liFccvE7lwcyFIkD
            clientSecret: a31eee77b2a839804814455e7d61db81510a4ae6

